language: python

matrix:
  include:
  - python: 3.7
  - python: 3.8
  - python: 3.9
  - python: 3.10
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
after_success:
  coveralls
deploy:
  provider: pypi
  user: khalas
  password:
    secure: "rrvTrcLSuZvIeMxP2A84WYB4I1Aea6ymGKuFInSjxReKhG+S9hmSuMyzZASbpGQftZUScCPI4SP3jJQMnEnUJC2jDp+lAjakxDS/E6NMtsIq2vboFG7sejo5LLFCk0vvFjlzZWagYohbMDdqiRT2JEqVnkfk5t2dinA2mgCucDg="
  on:
    tags: true
    branch: master
    python: '3.9'
